get:
  summary: Get Config Value Active by Server Group Config Condition
  deprecated: false
  description: ''
  tags:
    - Auto PO Configuration
  parameters:
    - name: configType
      in: path
      description: ''
      required: true
      example: setting_parameter
      schema:
        type: string
    - name: serverGroup
      in: path
      description: ''
      required: true
      example: BCG
      schema:
        type: string
    - name: configCondition
      in: path
      description: ''
      required: true
      example: skip_level_1_RFQ
      schema:
        type: string
  responses:
    '200':
      description: ''
      content:
        application/json:
          schema:
            type: object
            properties: {}
      headers: {}
    '401':
      $ref: '../components/responses/ErrorResponses.yaml#/Unauthorized'
    '400':
      $ref: '../components/responses/ErrorResponses.yaml#/BadRequest'
    '500':
      $ref: '../components/responses/ErrorResponses.yaml#/InternalServerError'
  security:
    - bearer: []
