post:
  summary: Submit new configuration
  deprecated: false
  description: |
    Create a new Auto PO configuration entry.
  operationId: submitConfig
  tags:
    - Auto PO Configuration
  parameters: []
  requestBody:
    content:
      application/json:
        schema:
          type: object
          properties: {}
        example:
          config_value: '1000000'
    required: true
  responses:
    '200':
      description: Configuration created successfully
      content:
        application/json:
          schema:
            type: object
            properties:
              message:
                type: string
              data:
                type: object
                properties: {}
      headers: {}
  security:
    - bearer: []
