Enum "board_card_is_priority_enum" {
  "0"
  "1"
}

Enum "board_card_complete_enum" {
  "1"
  "0"
  "2"
  "3"
  "4"
  "5"
  "6"
  "7"
  "8"
  "9"
}

Enum "board_card_split_for_enum" {
  "CL"
  "CS"
}

Enum "counter_split_pr_items_split_for_enum" {
  "CL"
  "CS"
}

Enum "history_report_cs_status_enum" {
  "Email to Requester"
  "TOR Completed"
  "RFQ Launched"
  "Bid Submission"
  "QCF Completed"
  "Winner Decision"
  "Contract Signed"
  "SAP PO Published"
}

Enum "history_report_cs_is_email_enum" {
  "0"
  "1"
}

Enum "item_card_item_complete_enum" {
  "1"
  "0"
  "2"
  "3"
  "4"
  "5"
  "6"
  "7"
  "8"
  "9"
}

Enum "report_cs_status_on_enum" {
  "Email to Requester"
  "TOR Completed"
  "RFQ Launched"
  "Bid Submission"
  "QCF Completed"
  "Winner Decision"
  "Contract Signed"
  "SAP PO Published"
}

Enum "report_cs_partial_status_on_enum" {
  "Email to Requester"
  "TOR Completed"
  "RFQ Launched"
  "Bid Submission"
  "QCF Completed"
  "Winner Decision"
  "Contract Signed"
  "SAP PO Published"
}

Enum "reset_report_cs_status_enum" {
  "Email to Requester"
  "TOR Completed"
  "RFQ Launched"
  "Bid Submission"
  "QCF Completed"
  "Winner Decision"
  "Contract Signed"
  "SAP PO Published"
}

Enum "reset_report_cs_is_email_enum" {
  "0"
  "1"
}

Table "board" {
  "id" "int unsigned" [pk, not null, increment]
  "user_id" "int unsigned" [not null]
  "boardTitle" varchar(255) [not null]
  "is_starred" tinyint(1) [not null]
  "boardPrivacyType" varchar(255) [not null]
  "created_at" timestamp
  "updated_at" timestamp

  Indexes {
    user_id [type: btree, name: "board_user_id_foreign"]
  }
}

Table "board_card" {
  "id" "int unsigned" [pk, not null, increment]
  "board_id" "int unsigned" [not null]
  "user_id" "int unsigned" [not null]
  "list_id" "int unsigned" [not null]
  "card_title" varchar(25)
  "card_description" text
  "card_color" varchar(10)
  "due_date" "timestamp on update CURRENT_TIMESTAMP" [not null, default: `CURRENT_TIMESTAMP`]
  "pr_company_groups" varchar(10)
  "company" int
  "is_priority" board_card_is_priority_enum [default: '0']
  "pr_release_date" datetime
  "pr_value" decimal(12,0) [default: 0, note: 'PR Value']
  "currency" varchar(10)
  "convert_value" bigint
  "convert_currency" varchar(5)
  "pr_material_group" varchar(100)
  "pr_service_group" varchar(100)
  "pr_material_group_number" varchar(10)
  "pr_service_group_number" varchar(10)
  "pr_requestor_user" varchar(100)
  "pr_requestor_email" varchar(150)
  "pr_creator_user" varchar(150)
  "pr_creator_email" varchar(200)
  "purchase_group" varchar(100)
  "complete" board_card_complete_enum [not null, default: '0', note: '0:onprogres\\r\\n1:complete\\r\\n2:inactive\\r\\n3:waitingCancel\\r\\n4:cancel\\r\\n5:waitingClose\\r\\n6:close\\r\\n7:waiting restore\\n8:RequestReject\\n9:autoClosed']
  "created_at" timestamp [not null, default: `CURRENT_TIMESTAMP`]
  "updated_at" timestamp
  "partial_status" varchar(5)
  "po_number" varchar(20)
  "spend_channel" varchar(45)
  "pr_risk" varchar(5)
  "pr_permit1" varchar(200)
  "pr_permit2" varchar(200)
  "pr_permit3" varchar(200)
  "purchase_group_code" varchar(50)
  "sources" varchar(10) [default: 'SAP']
  "pr_reff" varchar(100)
  "split_from" varchar(20)
  "split_no" int
  "split_for" board_card_split_for_enum
  "is_updated" tinyint(1) [default: 0]
  "tor_number" varchar(15)
  "tor_status" varchar(15)
  "tor_release_date" datetime
  "tor_link" text
  "im_number" varchar(20)

  Indexes {
    card_title [type: btree, name: "board_card_idx_card_title"]
    (complete, user_id, id) [type: btree, name: "board_card_idx_complete_user_id_id"]
    (complete, user_id, pr_release_date) [type: btree, name: "board_card_idx_complete_user_id_pr_date"]
    card_color [type: btree, name: "card_color"]
    company [type: btree, name: "company"]
    complete [type: btree, name: "complete"]
    (pr_release_date, complete, list_id, user_id, card_title) [type: btree, name: "complete_list_id_user_id_card_title_pr_release_date"]
    list_id [type: btree, name: "list_id"]
    user_id [type: btree, name: "user_id"]
  }
}

Table "board_list" {
  "id" "int unsigned" [pk, not null, increment]
  "board_id" "int unsigned" [not null]
  "user_id" "int unsigned" [not null]
  "asigned_id" int [not null]
  "list_name" varchar(255) [not null]
  "milestone_id" int
  "priority" int
  "created_at" timestamp
  "updated_at" timestamp

  Indexes {
    (list_name, asigned_id) [type: btree, name: "board_list_idx_asigned_id_list_name"]
  }
}

Table "board_risk" {
  "id" int [pk, not null, increment]
  "pr_risk_code" varchar(30)
  "pr_risk_name" varchar(30)
}

Table "card_tag" {
  "id" "int unsigned" [pk, not null, increment]
  "card_id" "int unsigned" [not null]
  "tag_title" varchar(255) [not null]
  "created_at" timestamp
  "updated_at" timestamp
}

Table "card_task" {
  "id" "int unsigned" [pk, not null, increment]
  "card_id" "int unsigned" [not null]
  "milestoneId" int
  "activity_id" int
  "task_title" varchar(255) [not null]
  "is_completed" tinyint(1) [not null]
  "created_at" timestamp
  "updated_at" timestamp
}

Table "category_group" {
  "cat_grp_id" int [pk, not null, increment]
  "cat_grp_code" varchar(10) [not null]
  "cat_grp_name" varchar(150) [not null]
  "cat_grp_color" varchar(10)
  "cat_grp_icon" varchar(10)
  "cat_board_list" int
  "cat_group_leader" int
  Note: 'Category Group'
}

Table "comment" {
  "id" "int unsigned" [pk, not null, increment]
  "card_id" "int unsigned" [not null]
  "user_id" "int unsigned" [not null]
  "comment_description" varchar(255) [not null]
  "created_at" timestamp
  "updated_at" timestamp
}

Table "companies" {
  "id" "int unsigned" [pk, not null, increment]
  "company_code" "int unsigned"
  "company_name" varchar(255)
  "groupId" varchar(10) [not null]
  "groupName" varchar(75) [not null]
  "created_at" datetime
  "updated_at" datetime
  "company_inisial" varchar(10)

  Indexes {
    company_code [type: btree, name: "company_code"]
  }
}

Table "contracts" {
  "id" "int unsigned" [pk, not null, increment]
  "pr_number" varchar(255) [not null]
  "checked" int [not null, default: 0]
  "created_at" timestamp
  "updated_at" timestamp
  "item_id" int [unique]

  Indexes {
    checked [type: btree, name: "checked"]
    pr_number [type: btree, name: "pr_number"]
  }
}

Table "counter_split_pr_items" {
  "id" int [pk, not null, increment]
  "card_id" int
  "pr_number" varchar(50)
  "item_id" int
  "created_at" timestamp
  "split_no" int
  "split_for" counter_split_pr_items_split_for_enum
}

Table "csi_rating" {
  "id" int [pk, not null, increment]
  "pr_number" varchar(100) [not null]
  "pr_desc" varchar(255)
  "pr_requestor" varchar(100)
  "pr_requestor_email" varchar(100)
  "cl_name" varchar(255)
  "cs_name" varchar(255)
  "pr_sla" int [default: 0]
  "csi_rating" int [default: 0]
  "csi_comment" text
  "csi_status" int [default: 0, note: '0 : new, 1 : send by cs (manual), 2 : send by system (auto)']
  "csi_name" varchar(255)
  "csi_email" varchar(255)
  "csi_rated" int [default: 0, note: '0 : not rated, 1 : rated by requestor, 2: rated by system']
  "csi_invitationstatus" mediumtext [note: 'terkirim / bounce']
  "csi_invitationdate" datetime [note: 'Tanggal terakhir kirim invitation csi']
  "csi_expireddate" date
  "csi_expmanual" date [note: 'expired untuk manual invitation']
  "created_at" datetime
  "updated_at" "timestamp on update CURRENT_TIMESTAMP" [default: `CURRENT_TIMESTAMP`]
  "po_number" varchar(150)
  "item_id" int

  Indexes {
    pr_number [type: btree, name: "idx_csi_rating_pr_number"]
  }
  Note: 'New CSI Rating Table'
}

Table "csi_rating_invitation" {
  "id" int [pk, not null, increment]
  "id_csi_rating" int [not null]
  "token" varchar(100) [not null]
  "is_valid" tinyint(1) [not null]
  "created_at" datetime [not null, default: `CURRENT_TIMESTAMP`]
  "updated_at" "datetime on update CURRENT_TIMESTAMP" [not null, default: `CURRENT_TIMESTAMP`]
}

Table "currency" {
  "id" int [pk, not null, increment]
  "currency_code" varchar(30)
  "currency_desc" varchar(60)
}

Table "exports" {
  "id" "int unsigned" [pk, not null, increment]
  "queue_number" int [not null]
  "company_group" varchar(255) [not null, default: '']
  "company_name" varchar(255) [not null, default: '']
  "pr_number" varchar(255) [not null, default: '']
  "card_description" varchar(255) [not null, default: '']
  "pr_value" varchar(255) [not null, default: '']
  "currency" varchar(255) [not null, default: '']
  "sap_release" varchar(255) [not null, default: '']
  "category" varchar(255) [not null, default: '']
  "cl" varchar(255) [not null, default: '']
  "cs" varchar(255) [not null, default: '']
  "email_start" varchar(255) [not null, default: '']
  "email_end" varchar(255) [not null, default: '']
  "email_sla" varchar(255) [not null, default: '']
  "tor_start" varchar(255) [not null, default: '']
  "tor_end" varchar(255) [not null, default: '']
  "tor_sla" varchar(255) [not null, default: '']
  "rfq_start" varchar(255) [not null, default: '']
  "rfq_end" varchar(255) [not null, default: '']
  "rfq_sla" varchar(255) [not null, default: '']
  "bid_start" varchar(255) [not null, default: '']
  "bid_end" varchar(255) [not null, default: '']
  "bid_sla" varchar(255) [not null, default: '']
  "qcf_start" varchar(255) [not null, default: '']
  "qcf_end" varchar(255) [not null, default: '']
  "qcf_sla" varchar(255) [not null, default: '']
  "winner_start" varchar(255) [not null, default: '']
  "winner_end" varchar(255) [not null, default: '']
  "winner_sla" varchar(255) [not null, default: '']
  "contract_start" varchar(255) [not null, default: '']
  "contract_end" varchar(255) [not null, default: '']
  "contract_sla" varchar(255) [not null, default: '']
  "sap_start" varchar(255) [not null, default: '']
  "sap_end" varchar(255) [not null, default: '']
  "sap_sla" varchar(255) [not null, default: '']
  "sla" varchar(255) [not null, default: '']
  "latest_status" varchar(255) [not null, default: '']
  "created_at" timestamp
  "updated_at" timestamp
}

Table "exports_data" {
  "id" "int unsigned" [pk, not null, increment]
  "pr_number" varchar(255) [not null, default: '']
  "board_id" int [not null]
  "company_group" varchar(255) [not null, default: '']
  "company_name" varchar(255) [default: '']
  "card_description" varchar(255) [default: '']
  "pr_requestor_user" varchar(100)
  "pr_requestor_email" varchar(150)
  "pr_creator_user" varchar(150)
  "pr_creator_email" varchar(200)
  "pr_value" bigint
  "currency" varchar(255) [default: '']
  "convert_value" bigint
  "convert_currency" varchar(5)
  "sap_release" varchar(255) [default: '']
  "sourcing_type" int
  "category" varchar(255) [default: '']
  "cl_board_id" int
  "cl_user_id" int
  "cl" varchar(255) [default: '']
  "cs_board_id" int
  "cs_user_id" int
  "cs" varchar(255) [default: '']
  "email_start" varchar(255) [default: '']
  "email_end" varchar(255) [default: '']
  "email_sla" varchar(255) [default: '']
  "tor_start" varchar(255) [default: '']
  "tor_end" varchar(255) [default: '']
  "tor_sla" varchar(255) [default: '']
  "rfq_start" varchar(255) [default: '']
  "rfq_end" varchar(255) [default: '']
  "rfq_sla" varchar(255) [default: '']
  "bid_start" varchar(255) [default: '']
  "bid_end" varchar(255) [default: '']
  "bid_sla" varchar(255) [default: '']
  "qcf_start" varchar(255) [default: '']
  "qcf_end" varchar(255) [default: '']
  "qcf_sla" varchar(255) [default: '']
  "winner_start" varchar(255) [default: '']
  "winner_end" varchar(255) [default: '']
  "winner_sla" varchar(255) [default: '']
  "contract_start" varchar(255) [default: '']
  "contract_end" varchar(255) [default: '']
  "contract_sla" varchar(255) [default: '']
  "sap_start" varchar(255) [default: '']
  "sap_end" varchar(255) [default: '']
  "sap_sla" varchar(255) [default: '']
  "sla_target" int
  "sla" varchar(255) [default: '']
  "latest_status" varchar(255) [default: '']
  "created_at" timestamp
  "updated_at" timestamp
  "is_priority" varchar(5)
  "pr_remark" text
  "notes" text
  "pr_release_date" datetime
  "company_code" varchar(45)
  "card_color" varchar(7)
  "complete" varchar(1) [default: 0]
  "pr_status" varchar(45)
  "partial_status" varchar(5)
  "sourcing_method" varchar(45)
  "tor_remark" text
  "rfq_remark" text
  "bid_remark" text
  "qcf_remark" text
  "winner_remark" text
  "contract_remark" text
  "sap_remark" text
  "hold_date_1" date
  "resume_date_1" date
  "hold_date_2" date
  "resume_date_2" date
  "hold_date_3" date
  "resume_date_3" date
  "hold_date_4" date
  "resume_date_4" date
  "hold_date_5" date
  "resume_date_5" date
  "hold_date_6" date
  "resume_date_6" date
  "hold_date_7" date
  "resume_date_7" date
  "hold_date_8" date
  "resume_date_8" date
  "hold_date_9" date
  "resume_date_9" date
  "hold_date_10" date
  "resume_date_10" date
  "sla_unassigned" int [default: 0]
  "sla_paused" int [default: 0]
  "start_process" timestamp [not null, default: `CURRENT_TIMESTAMP`]
  "end_process" timestamp
  "need_contract" int [default: 0]
  "isourcing_in" datetime
  "isourcing_out" datetime
  "pr_risk" varchar(5)
  "pr_permit1" varchar(200)
  "pr_permit2" varchar(200)
  "pr_permit3" varchar(200)
  "assign_to_cl" date
  "assign_to_cs" date
  "sla_assignCl" int [default: 0]
  "sla_assignCS" int [default: 0]
  "sla_totalHold" int [default: 0]
  "item_description" text
  "pr_item_value" int
  "qty" int
  "item_id" int
  "po_number" varchar(20)
  "oa_number" varchar(15)
  "oa_valid_end" date
  "oa_category" varchar(15)
  "oa_requester" varchar(150)
  "item_code" varchar(25)
  "is_updated" tinyint(1) [default: 0, note: 'untuk mapping data setelah rotasi cl dan cs']
  "is_delete" tinyint(1) [default: 0]

  Indexes {
    (cs, cl, cl_user_id, cs_user_id) [type: btree, name: "cl_user_id"]
    (company_name, company_group) [type: btree, name: "company_group"]
    pr_number [type: btree, name: "idx_exports_data_pr_number"]
    is_priority [type: btree, name: "is_priority"]
    item_id [type: btree, name: "item_id"]
    (pr_status, complete, pr_release_date) [type: btree, name: "pr_release_date"]
    (pr_creator_email, pr_creator_user, pr_requestor_email, pr_requestor_user) [type: btree, name: "pr_requestor_user"]
  }
}

Table "failed_jobs" {
  "id" "int unsigned" [pk, not null, increment]
  "connection" text [not null]
  "queue" text [not null]
  "payload" longtext [not null]
  "failed_at" timestamp [not null, default: `CURRENT_TIMESTAMP`]
}

Table "flag_download" {
  "flag" int [pk, not null]
  "created_at" timestamp
  "updated_at" timestamp
}

Table "history_log_assign" {
  "id" int [pk, not null, increment]
  "pr_number" varchar(50) [not null]
  "item_id" int [not null]
  "item_code" varchar(5) [not null]
  "level_category" varchar(10) [not null]
  "category" varchar(10) [not null]
  "user_name" varchar(200) [not null]
  "activity" varchar(50) [not null]
  "assign_start" datetime
  "assign_end" datetime
  "created_at" datetime [not null, default: `CURRENT_TIMESTAMP`]
  "updated_at" datetime [not null, default: `CURRENT_TIMESTAMP`]

  Indexes {
    (activity, category) [type: btree, name: "idx_category_activity"]
  }
  Note: 'history log'
}

Table "history_report_cs" {
  "id" int [pk, not null, increment]
  "pr_number" varchar(100)
  "user_id" int [not null]
  "status" history_report_cs_status_enum [not null]
  "notes" varchar(255)
  "is_email" history_report_cs_is_email_enum [not null, default: '0']
  "pause_date" datetime
  "resume_date" datetime
  "created_at" datetime
  "updated_at" datetime
  "item_id" int

  Indexes {
    (updated_at, created_at) [type: btree, name: "created_at"]
    item_id [type: btree, name: "item_id"]
    (pr_number, status) [type: btree, name: "statusPR"]
  }
}

Table "iss_pr_vendor_recommendation" {
  "id" int [pk, not null, increment]
  "server" varchar(10)
  "pr_number" varchar(15)
  "pr_item" int
  "sap_kbli" varchar(10)
  "sap_tingkat_risiko" varchar(10)
  "ranking" int
  "vendor_name" varchar(50)
  "kode_sap" varchar(10)
  "kode_ariba" varchar(15)
  "status_sio" varchar(20)
  "tanggal_expired_sio" date
  "nilai_pq" int
  "vendor_tingkat_risiko" varchar(20)
  "tanggal_berakhir_pq" date
  "status_pq" varchar(10)
  "send_date" date
}

Table "item_card" {
  "id" int [pk, not null, increment]
  "pr_number" varchar(100)
  "item_code" varchar(15) [not null]
  "text" text [not null]
  "qty" int [not null, default: 0]
  "unit" varchar(10)
  "pr_item_value" int [not null]
  "pr_release_date" datetime [not null]
  "pr_close" varchar(45)
  "created_at" "timestamp on update CURRENT_TIMESTAMP" [not null, default: `CURRENT_TIMESTAMP`]
  "updated_at" "timestamp on update CURRENT_TIMESTAMP" [not null, default: `CURRENT_TIMESTAMP`]
  "region" varchar(20)
  "price_item_idr" bigint
  "acc_assign" varchar(10)
  "assigned_to_cl" int
  "send_email_to" int
  "assigned_to_cs" int
  "partial_status" varchar(25)
  "split_from_id" int
  "item_complete" item_card_item_complete_enum [not null, default: '0', note: '0:onprogres\\r\\n1:complete\\r\\n2:inactive\\r\\n3:waitingCancel\\r\\n4:cancel\\r\\n5:waitingClose\\r\\n6:close\\r\\n7:waiting restore\\n8:autoCancel\\n9:autoClosed']
  "is_repeatorder" tinyint(1)
  "text_repeatorder" text
  "po_number" varchar(150)
  "po_qty" int [default: 0]
  "po_create_date" datetime
  "is_updated" tinyint(1) [default: 0, note: 'untuk mapping data setelah rotasi cl dan cs']
  "is_delete" tinyint(1) [default: 0]
  "is_newitem" tinyint(1)
  "pr_material_group" varchar(255)
  "pr_material_group_number" varchar(45)
  "nomor_material_sap" varchar(18)
  "plant_code" varchar(4)
  "garansi" tinyint
  "brand" varchar(50)
}

Table "jobs" {
  "id" "bigint unsigned" [pk, not null, increment]
  "queue" varchar(255) [not null]
  "payload" longtext [not null]
  "attempts" "tinyint unsigned" [not null]
  "reserved" "tinyint unsigned" [not null]
  "reserved_at" "int unsigned"
  "available_at" "int unsigned" [not null]
  "created_at" "int unsigned" [not null]

  Indexes {
    (queue, reserved, reserved_at) [type: btree, name: "jobs_queue_reserved_reserved_at_index"]
  }
}

Table "material_cat_group" {
  "material_id" int [pk, not null, increment]
  "material_number" varchar(10)
  "material_name" varchar(255)
  "category_group_id" int
  "server_material" varchar(10)
  Note: 'material category group'
}

Table "matrix_assign_gsheet" {
  "SERVER" varchar(10)
  "Material_group" varchar(10)
  "Material_group_name" varchar(60)
  "SOP" varchar(10)
  "HISTORY_TRX" varchar(10)
  "Category" varchar(10)
  "Note" varchar(10)
}

Table "migrations" {
  "id" int [pk, not null, increment]
  "migration" varchar(255) [not null]
  "batch" int [not null]
  "upload_date" datetime [not null]
  "start_date" datetime
  "end_date" datetime
  "created_at" timestamp
  "updated_at" timestamp
  "total_rows" bigint [not null]
  "tipe" varchar(5) [not null]
}

Table "milestone_activity_config" {
  "id" int [pk, not null, increment]
  "milestone_id" int [not null]
  "activity_name" varchar(255)
  "created_at" datetime
  "update_at" timestamp
  Note: 'untuk master data list activity per milestone'
}

Table "milestone_config" {
  "id" int [pk, not null, increment]
  "status_milestone" varchar(250) [not null]
  "tender" int [not null]
  "selection" int [not null]
  "appointment" int [not null]
  "created_at" timestamp [not null, default: `CURRENT_TIMESTAMP`]
}

Table "password_resets" {
  "email" varchar(255) [not null]
  "token" varchar(255) [not null]
  "created_at" "timestamp on update CURRENT_TIMESTAMP" [not null, default: `CURRENT_TIMESTAMP`]

  Indexes {
    email [type: btree, name: "password_resets_email_index"]
    token [type: btree, name: "password_resets_token_index"]
  }
}

Table "pr_approval" {
  "approval_id" int [pk, not null, increment]
  "pr_number" varchar(20) [not null]
  "item_id" int
  "user_id" int [not null]
  "pr_activity" varchar(25)
  "pr_app_code" varchar(25) [note: '1=Request(closePR, PausePR, Reset), 2=approved(closePR, PausePR, Reset); 3=rejected']
  "app_status" int [not null, note: '1 = REQ, 2 = APPROVE , 3 = REJECTED']
  "created_at" datetime
  "approve_at" datetime
  "app_comment" text
  "reject_comment" text
  "app_sequence" int [default: 0]
  "file_restore" varchar(200)

  Indexes {
    (user_id, item_id) [type: btree, name: "item_id"]
    (pr_activity, pr_app_code) [type: btree, name: "pr_activity"]
    pr_number [type: btree, name: "pr_number"]
  }
  Note: 'Notifikasi Approval Table'
}

Table "pr_logs" {
  "id" int [pk, not null, increment]
  "pr_number" varchar(100)
  "server" varchar(10)
  "pr_start_date" datetime
  "pr_end_date" datetime
  "created_at" timestamp [not null, default: `CURRENT_TIMESTAMP`]
  "updated_at" timestamp
  "assigned_to_cs" datetime
  "assigned_to_cl" datetime
  "item_id" int
  "oa_number" varchar(15)
  "oa_valid_end" date
  "oa_category" varchar(15)
  "oa_requester" varchar(150)
}

Table "pr_movements" {
  "id" "int unsigned" [pk, not null, increment]
  "pr_number" varchar(255) [unique, not null, default: '']
  "category" varchar(255) [not null, default: '']
  "first_cl" int [not null]
  "first_cs" int [not null]
  "end_cl" int [not null]
  "end_cs" int [not null]
  "created_at" timestamp
  "updated_at" timestamp
}

Table "pr_torpaused" {
  "torpaused_id" int [pk, not null, increment]
  "pr_number" varchar(100) [not null]
  "item_id" int
  "user_id" int
  "reason_code" varchar(80) [not null]
  "reason_comment" text
  "paused_date" datetime
  "resume_date" datetime
  "status_tor" int [not null, note: '1=request,2=approved,3=resume,4=reject']
  "paused_leadtime" int [not null]
  "created_at" datetime [not null, default: `CURRENT_TIMESTAMP`]
  "milestone" varchar(45)
  "unhold_comment" text

  Indexes {
    pr_number [type: btree, name: "idx_pr_torpaused_pr_number"]
    item_id [type: btree, name: "item_id"]
    status_tor [type: btree, name: "status_tor"]
    user_id [type: btree, name: "user_id"]
  }
  Note: 'TOR Paused'
}

Table "reason" {
  "id" int [pk, not null, increment]
  "reason" varchar(80)
  "milestone" varchar(50)
}

Table "remark" {
  "id" "int unsigned" [pk, not null, increment]
  "pr_number" varchar(100) [not null]
  "user_id" "int unsigned" [not null]
  "status_milestone" varchar(25) [not null, note: 'status_milestone']
  "sourcing_method" varchar(15) [not null]
  "remark_status" int [not null, note: '1=Sourcing, 2=Milestone, 3=PR_Desc']
  "remark_notes" text
  "created_at" timestamp [default: `CURRENT_TIMESTAMP`]
  "updated_at" timestamp [default: `CURRENT_TIMESTAMP`]
}

Table "report_cs" {
  "id" int [pk, not null, increment]
  "pr_number" varchar(100)
  "sourcing_method" int
  "status_on" report_cs_status_on_enum [not null]
  "created_at" timestamp [not null, default: `CURRENT_TIMESTAMP`]
  "updated_at" timestamp [not null, default: `CURRENT_TIMESTAMP`]
  "item_id" int

  Indexes {
    item_id [type: btree, name: "item_id"]
    pr_number [type: btree, name: "report_cs_idx_pr_number"]
    (updated_at, status_on, pr_number) [type: btree, name: "report_cs_idx_status_on_pr_number_updated_at"]
    status_on [type: btree, name: "status_on"]
  }
}

Table "report_cs_partial" {
  "id" int [pk, not null, increment]
  "pr_number" varchar(15) [not null]
  "sourcing_method" int
  "status_on" report_cs_partial_status_on_enum [not null]
  "created_at" timestamp [not null, default: `CURRENT_TIMESTAMP`]
  "updated_at" timestamp [not null, default: `CURRENT_TIMESTAMP`]
}

Table "report_weekly" {
  "id" int [pk, not null, increment]
  "first_date" date [not null]
  "last_date" date [not null]
  "value" varchar(11) [not null]
  "complete" int [not null]
  "on_going" int [not null]
  "new" int [not null]
  "total_pr" int [not null]
  "user_id" int [not null]
}

Table "reset_pr_approval" {
  "approval_id" int [not null]
  "pr_number" varchar(20) [not null]
  "item_id" int
  "user_id" int [not null]
  "pr_activity" varchar(15)
  "pr_app_code" varchar(25) [note: '1=Request(closePR, PausePR, Reset), 2=approved(closePR, PausePR, Reset); 3=rejected']
  "app_status" int [not null, note: '1 = REQ, 2 = APPROVE , 3 = REJECTED']
  "created_at" datetime
  "approve_at" datetime
  "app_comment" text
  "reject_comment" text
  "app_sequence" int [default: 0]
  Note: 'Notifikasi Approval Table'
}

Table "reset_pr_torpaused" {
  "torpaused_id" int [not null]
  "pr_number" varchar(15) [not null]
  "item_id" int
  "user_id" int
  "reason_code" varchar(80) [not null]
  "reason_comment" text
  "paused_date" datetime
  "resume_date" datetime
  "status_tor" int [not null, note: '1=req,2=app,3=resume,4=reject']
  "paused_leadtime" int [not null]
  "created_at" datetime [not null, default: `CURRENT_TIMESTAMP`]
  "milestone" varchar(45)
  "unhold_comment" text
  Note: 'TOR Paused'
}

Table "reset_report_cs" {
  "id" int [not null]
  "pr_number" varchar(100) [not null]
  "user_id" int [not null]
  "status" reset_report_cs_status_enum [not null]
  "notes" varchar(255)
  "is_email" reset_report_cs_is_email_enum [not null, default: '0']
  "pause_date" datetime
  "resume_date" datetime
  "created_at" datetime
  "updated_at" datetime
  "item_id" int
}

Table "sap_plant" {
  "server" varchar(4) [not null]
  "company_code" varchar(10) [not null, default: '']
  "company_name" varchar(50)
  "plant_code" varchar(10)
  "plant_name" varchar(50)
  "region" varchar(40)
  "alamat" text
  "send_date" datetime
}

Table "sap_pr_header" {
  "pr_number" varchar(11) [pk, not null]
  "is_closed" tinyint [not null]
  "closed_reason" varchar(11)
  "purch_grp_code" char(3)
  "purch_grp_dept_head_name" varchar(200)
  "purch_grp_dept_head_email" varchar(200)
  "send_date" datetime
}

Table "schema_migrations_task_board" {
  "version" varchar(20) [pk, not null]
  "applied_at" timestamp [default: `CURRENT_TIMESTAMP`]
}

Table "sessions" {
  "id" varchar(255) [not null]
  "user_id" int
  "ip_address" varchar(45)
  "user_agent" text
  "payload" text [not null]
  "last_activity" int [not null]
}

Table "sop_matrix_assign" {
  "Server" varchar(50) [not null]
  "﻿material_group" varchar(40) [not null]
  "material_group_name" varchar(40) [not null]
  "cat_grp_name" varchar(10) [not null]
}

Table "sourcing_method" {
  "id" int [pk, not null, increment]
  "name" varchar(100) [not null]
  "created_at" timestamp [not null, default: `CURRENT_TIMESTAMP`]
  "update_at" timestamp [not null, default: `CURRENT_TIMESTAMP`]
}

Table "user_activity" {
  "id" int [pk, not null, increment]
  "user_id" "int unsigned" [not null]
  "changed_in" varchar(255) [not null]
  "activity_in_id" int [not null]
  "activity_description" text [not null]
  "created_at" timestamp
  "updated_at" timestamp
}

Table "user_authlog" {
  "id" int [pk, not null, increment]
  "user_id" "int unsigned" [not null]
  "log_type" varchar(255)
  "log_description" text
  "ip_address" varchar(20)
  "user_agent" varchar(150)
  "url" text
  "created_at" datetime
  "updated_at" datetime
  Note: 'untuk handle log authentication'
}

Table "user_rate" {
  "id" "int unsigned" [pk, not null, increment]
  "pr_number" varchar(255) [not null]
  "po_number" varchar(255) [not null]
  "creator_name" varchar(255) [not null]
  "requestor_name" varchar(255) [not null]
  "rate" tinyint [not null]
  "comment" text [not null]
  "created_at" timestamp
  "updated_at" timestamp
  "cl_name" varchar(150)
  "cs_name" varchar(150)
}

Table "users" {
  "id" "int unsigned" [pk, not null, increment]
  "name" varchar(255) [not null]
  "level" int [not null]
  "asigned_by" int [not null]
  "email" varchar(255) [not null]
  "username" varchar(255) [not null, default: '']
  "password" varchar(60) [not null]
  "remember_token" varchar(100)
  "active" int [not null, default: 0]
  "created_at" timestamp
  "updated_at" timestamp
  "token" varchar(250) [not null]
  "popup" tinyint(1) [default: 0]
  "popup_updated_at" timestamp [default: `CURRENT_TIMESTAMP`]

  Indexes {
    asigned_by [type: btree, name: "asigned_by"]
    (asigned_by, id) [type: btree, name: "users_idx_asigned_by_id"]
  }
}

Table "users_migrasi" {
  "id" "int unsigned" [pk, not null, increment]
  "name" varchar(255) [not null]
  "level" int [not null]
  "asigned_by" int [not null]
  "email" varchar(255) [not null]
  "username" varchar(255) [not null, default: '']
  "password" varchar(60) [not null]
  "remember_token" varchar(100)
  "created_at" timestamp
  "updated_at" timestamp
  "token" varchar(250) [not null]
}

Table "work_holiday" {
  "id" int [pk, not null, increment]
  "tanggal" date [not null]
  "freeday" varchar(2)
  "holiday" varchar(2)
  "is_weekend" tinyint(1)
}
